### ISSUE TITLE
Addition of "engines": { "node": ">=0.12"} is a breaking change

### ISSUE THREAD

**Issue by TattdCodeMonkey** [feross/is-buffer#13]
Just FYI adding  `"engines": { "node": ">=0.12"}` that came [here](https://github.com/feross/is-buffer/commit/b13fb38c8e42359c6b0a46d2921b88df8e7bc2e7) is a breaking change.

**Comment by feross** [comment]
Sorry if that affected you. Background on the change is here: https://github.com/feross/is-buffer/issues/2

It should only cause a warning -- not prevent installation.

**Comment by TattdCodeMonkey** [comment]
Your are correct, sorry. mistook the warning for an error and the real error was something else. My deepest apologies.

**Comment by bajtos** [comment]
Hello, I am convinced too that this was a breaking change that should have been released in a new major version per http://semver.org/ 😞 Projects depending on `"is-buffer": "^1.0.0"` and running on Node v0.10 will start reporting installation warnings.

Node v0.10 is still a supported LTS version with many users running on it.

For example, our API Framework http://loopback.io/ targets enterprise users where Node v0.10 is still very common. We use tools that depend on `is-buffer` (transitively via dependencies) and now we are getting a bunch of installation warnings because of this change. These warnings puts us, LoopBack maintainers into bad light, like we are lames that cannot fix warnings. But in fact, there is nothing we can do about them, unless we downgrade our dependencies to ancient versions that depend on 0.x version of is-buffer (assuming there were such).

@feross could you please unpublish `is-buffer@1.1.3` and re-publishing this breaking change as a new major version?

**Comment by feross** [comment]
@bajtos Adding a new install-time warning is not a breaking change -- everything will continue to work.

This package doesn't detect SlowBuffer correctly on Node v0.10 -- and that has always been the case -- so it's important to warn users about it. See https://github.com/feross/is-buffer/issues/2#issuecomment-193477316 for background.

**Comment by bajtos** [comment]
@feross thank you for a quick reply! I have a different opinion on install-time warnings, I think it makes us (LoopBack maintaners) look lame like we cannot fix our dependencies to have a clean install. However, let's not waste our time discussing that, I am ok to agree that we disagree :)

I submitted a patch that fixes detection of SlowBuffer on Node v0.10, could you please take a look? https://github.com/feross/is-buffer/pull/15
